.github/workflows/test.yml, tests/test_collection/test_collection.py, tests/test_page.py
Add a new GitHub Action definition to run the RenderEngine test suite.
This configuration runs tests on pull requests and the `main` branch.
Failing tests are marked with `pytest.mark.xfail(strict=True)` to be
addressed in their own commits and pull requests.
=> Run tests in CI

docs/docs/collection.md, docs/docs/index.md, docs/docs/page.md, docs/docs/site.md, docs/mkdocs.yml, docs/requirements.txt, pyproject.toml
Add a new markdown document for each referenced object in the existing documentation. These documents use [mkdocstrings](https://mkdocstrings.github.io/) (a newly added documentation dependency) to generate autodoc-like documentation for the relevant Render Engine modules. Finally, resolve broken link warnings raised by `mkdocs build` by changing the links to match the ["Linking to pages" documentation](https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages) from mkdocs.
=> Add missing documentation pages for referenced objects

docs/requirements.txt, pyproject.toml
PR #53 included the mkdocstrings requirement but accidentally omitted the python extras specifier, causing a docs build failure.
=> Update mkdocstrings requirement

docs/mkdocs.yml, src/render_engine/page.py
Add markdown_extensions settings required to render the note and warning elements and convert the note and warning in the `Page` source to use mkdocs syntax instead of sphinx.
=> Fix note and warning block rendering

pyproject.toml
- Update readme key to point to correct file path in pyproject.toml
- Add homepage, repository, and documentation links to pyproject.toml
=> Correct readme, add links to pyproject.toml

src/render_engine/render_engine_templates/rss2.0.xml, src/render_engine/render_engine_templates/rss2.0_items.xml, tests/conftest.py, tests/test_feeds.py
These templates used to work when using the StrictUndefined undefined behavior in the jinja2 environment, but in recent releases, this causes the build to fail. This issue can be seen at
https://github.com/Python-Community-News/Site/pull/38. Using the `is defined` test results in similar behavior even when `StrictUndefined` is set, allowing site developers to catch typos or other missing template context without breaking their rss feeds.
This change also includes a new test and a test fixture to create a jinja2 environment that can be modified with the scope of a single test.
=> Handle undefined variables in rss templates

requirements.txt
Reverts kjaymiller/render_engine#138
mkdocstings still requires markdown 3.3.7.
=> Revert "Bump markdown from 3.3.7 to 3.4.3"

.github/dependabot.yml
Currently we are using mkdocs as a documentation framework. mkdocs has pinned the `Markdown` dependency to 3.3.X as to not potentially break extensions.
In the future we will no be using mkdocs in favor for render_engine building it's own documentation.
render_engine uses  markdown2 so in the future Markdown will not be a dependency.
=> add dependabot ignore for Markdown 3.4.X

src/render_engine/archive.py, src/render_engine/blog.py, src/render_engine/collection.py, src/render_engine/engine.py, src/render_engine/render_engine_templates/rss2.0_items.xml, src/render_engine/site.py, tests/test_blog.py, tests/test_feeds.py
Fully removes references to `date_published`/`date_modified` in favor of a single `date` value that blog is concerned about.
=> 2023.4.2a1-dates-conversion

.github/dependabot.yml
Fixes #168
Moves pip interval to weekly
=> change dependabot to weekly

docs/docs/site.md, src/render_engine/site.py, tests/test_site.py
changes many of the methods in Site to private methods. This removes them from documentation as these are meant to be used internally and not by users or plugin developers.
resolves #87
Check Collection and Page for the same issues.
=> Makes many functions private

docs/docs/plugins.md, docs/mkdocs.yml, src/render_engine/hookspecs.py, src/render_engine/plugins.py, src/render_engine/site.py, tests/test_plugins.py
Fixes #210
Creates `ignore_plugins` for page and collection objects
resolves #210
=> ➕: Adds `page.ignore_paths`

src/render_engine/_base_object.py, src/render_engine/feeds.py, src/render_engine/render_engine_templates/rss2.0.xml, tests/conftest.py, tests/test_base_object.py, tests/test_feeds.py
changes:
- adds `Page.path_name` to `Page.to_dict()`
- changes atom:link to `<SITE_URL>/<path_name>`
build steps:
resolves #171
=> set rss <atom:link> to link to rss link

src/render_engine/render_engine_templates/rss2.0.xml
Uses the {{path_name | to_absolute}} instead of combining SITE_URL/PATH_NAME
=> uses path_file | to absolute

src/render_engine/engine.py, tests/test_engine.py
Fixing the format_datetime to accept user input, and if found, render it instead of the site default.
- [ x ] :bug: (bug)
resolves #253
=> fix datetime filter for proper Jinja rendering

src/render_engine/hookspecs.py, src/render_engine/site.py
Adds site and settings to the `post_render_content` hookspec
This was in support for the internationlization plugin in development
=> Updates post_render_content

src/render_engine/page.py, src/render_engine/site.py, tests/test_site.py
now `render_content` and `post_render_content` only run in `site._render_output`
Lots of documenation around how plugins work (for both users and developers)
=> 🛠️ [FIX] render_engine_hook-in-render_output in one location

docs/docs/archive.md, docs/docs/collection.md, src/render_engine/collection.py, tests/conftest.py, tests/test_plugins.py
You can set enabled an Archive by setting `has_archive` to `True`, or setting the `items_per_page` attribute.
=> hard_code default template for archive

src/render_engine/utils/themes.py, tests/test_theme_manager.py
Some themes don't have static paths so the attribute should be optional
=> make static site optional for themes

docs/docs/custom_collections.md, src/render_engine/cli.py, src/render_engine/collection.py, src/render_engine/render_engine_templates/base.html, src/render_engine/site.py, src/render_engine/utils/themes.py, tests/test_theme_manager.py
Creates required_themes for collection items.
Required themes are used for custom collections to ensure that the required theme templates are installed.
The other change was to create simple expandability for custom themes and that was to remove the copying of the `base.html` theme from the quickstart.
In practice none of the template files need to be included  as they are already loaded but these were being exported using the `{%raw%}` expression. This was causing custom templates to not inherit from them properly.
If we were going to add the `base.html` back (as a placeholder to be customized) - the template files should be separated and copied separately.
=> required_themes and removes base.html from copied templates

pyproject.toml, tests/tests_cli/test_cli_builds_app.py
=> fixes static path in `render-engine init`

docs/docs/getting-started/creating-a-page.md
IF you use a decorator like that with parenthesis, you get this error:
`TypeError: Site.page() missing 1 required positional argument: 'Page'`
Remove the parenthesis and it works fine
=> Update creating-a-page.md to remove parens

pyproject.toml
The README specifies you need Python 3.9+ but you can install it on older versions (found this out the hard way) and it doesn't work.
This specifier will tell you at install time that your Python version is too old
=> Add minimum python requirement to pyproject.toml

src/render_engine/cli/cli.py, src/render_engine/render_engine_templates/create_app_py.txt, tests/tests_cli/conftest.py, tests/tests_cli/test_cli_builds_app.py
=> render-engine init --skip-static still updates the static path

src/render_engine/cli/cli.py
This pull request fixes the 'render_engine serve' command in the codebase that was causing an AttributeError. 
The issue was resolved by moving default values for the 'reload', 'directory', and 'port'  parameters in the 'serve' function to the correct position. This fix addresses #431.
=> Fix 'render_engine serve' AttributeError

src/render_engine/site.py, tests/test_site.py
This pull request fixes the register_theme function by updating the code to correctly register plugins from a theme. 
It also adds a test to ensure that a plugin added to a theme is properly added to the site.
=> Fix register theme and add test

docs/docs/hookspecs.md, docs/mkdocs.yml, src/render_engine/extras/clean_output.py, src/render_engine/extras/site_map.py, src/render_engine/plugins.py, tests/test_plugins.py, tests/test_site.py
This pull request moves the plugins from the `hookspecs.py` file to the `plugins.py` file for better organization.
=> Move plugins into plugins.py

src/render_engine/site.py, tests/test_plugins.py
=> Can't overwrite plugins_settings when registering values since `update` is called.

src/render_engine/render_engine_templates/archive.html
Fixes #520
Fixes the `archive.html` call for `url_for`.
=> Fix url_for() in template calls

src/render_engine/cli/cli.py, tests/tests_cli/test_render_engine_tools.py
This pull request fixes the clean_folder function in the CLI module. Previously, the function was passed in string. 
This PR also adds a test case to ensure that files and folders are properly removed when using the clean_folder function.
=> Fix clean folder function

.devcontainer/setup.sh, pyproject.toml
Fixes #556
In a recent refactor of tests we actually removed the need for pytest-lazy-fixture and could remove the dependency completely
=> remove pinning from test and pytest-lazy-fixture

.markdownlint.json, docs/docs/plugins.md
Fixes #571 
adds documentation for
- register_plugins
- ignoring_plugins
- single collection/page registration
I didn't see tests for single/collection page registration. It would be good to do that
=> 📖  update plugin docs

docs/docs/archive.md, docs/docs/cli.md, docs/docs/collection.md, docs/docs/feeds.md, docs/docs/hookspecs.md, docs/docs/page.md, docs/docs/parsers.md, docs/docs/site.md
fix #510
I also fixed some wrong paths in the docs and this:
Apparently some stuff was not rendering.
=> docs: convert to markdown and fix paths

src/render_engine/cli/cli.py
The pattern r".__.+$" is not valid because it contains .+ which is an invalid sequence in regex.
In regex, means "zero or more of the preceding element" and + means "one or more of the preceding element". So .+ is an invalid combination because it's unclear whether it should match zero or more or one or more of the preceding element.
If you want to match any string that contains two underscores, you can use the following pattern:
r".__.*$"
=> fix #606 serve regex

pyproject.toml, src/render_engine/cli/cli.py, src/render_engine/cli/event.py, src/render_engine/collection.py, src/render_engine/engine.py, src/render_engine/page.py, src/render_engine/site.py, src/render_engine/themes.py, tests/conftest.py, tests/test_archive.py, tests/test_collections.py, tests/test_engine.py, tests/test_feeds/conftest_feed.py, tests/test_feeds/test_feeds.py, tests/test_page.py, tests/test_plugins.py, tests/test_site.py, tests/test_templates/test_base_html.py, tests/test_theme_manager.py, tests/tests_cli/test_render_engine_cli.py, tests/tests_cli/test_render_engine_init.py
resolves #728, #729
- rename variable of Site object in cli `app` to `site`
- implements watchfiles
- creates `get_site_content_paths` to set reload on all content_paths 
- implements a context_manager for the cli
- creates `stop_watcher` method to allow for simpler testing
- implements tests for start_server/stop_server
=> refactor-cli

.github/dependabot.yml
Changing Interval of schedule from weekly to monthly
In dependabot.yml, the the workflow is scheduled weekly. To make the workflow only run once a month, I have changed the schedule to be monthly. This will run first of every month.
#770
=> Run Dependabot monthly

.github/PULL_REQUEST_TEMPLATE.md
Changed heading levels from H1/H2 to H4 in the PULL_REQUEST_TEMPLATE.md to maintain consistency with GitHub’s default H3 headings. This improves accessibility for screen readers by providing a logical heading structure.
=> fix: adjust heading levels in PR template for accessibility

src/render_engine/blog.py, src/render_engine/collection.py, tests/test_blog.py
Some RSS Readers are not working with Render Engine posts due to truncating the items list to the first `n` items.
Jekyll and Django both get around this with their feeds having the most recent content on top.
This change does that by making the feed pages pull from `sorted_pages`` (also used in the  `archive` object and the `latest` method) instead of iterating through pages.
This means that this functionality can be overridden if you manually set `_sort_reverse`.
=> Sorts the RSS Feeds based on Collection Settings 

.github/labeler.yml, .github/workflows/labeler.yml
This pull request includes changes to the GitHub Actions configuration to automate the labeling of pull requests based on specific criteria.
- [-] YES - Changes have been documented
- [-] YES - Changes have been tested
=> add auto labeler

.github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/test.yml
Added caching of pip to the GitHub workflows. This is done to speed pip installation workflows without adding any additional dependencies.
This reduces costs, especially in our more expensive images like macOS and Windows OS.
- [ x] :dizzy: (New Feature)
=> Caching workflows

.github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/test.yml
Change caching to utilize setup-python caching instead of adding a new dependency
- [-] YES - Changes have been documented
=> cache with setup python instead of introducting new step

.pre-commit-config.yaml, pyproject.toml, src/render_engine/blog.py, src/render_engine/collection.py, tests/test_blog.py
Removes the default value for iterating through `sorted_pages`
Fixing this revealed a new bug instead of defaulting to `title` which is defined,
it should default to `_title` which will default ultimately.
=> removes default value and changes sort to _title

src/render_engine/cli/cli.py
Addresses Issue #856 
- When `title` is passed to the template renderer it causes an issue because of a duplicate keyword value being passed. Since the duplication actually occurs in an external library this is handled by removing it from the args passed to the creation tools and then updating the rendered file using regex.
- Added validation for `args`
- Args can be separated by either `:` or `=`
- Duplicate args are not allowed
Probably not a bad idea to add some testing for `new_entry`. Since no unit tests existed for this function I didn't add at this point.
=> Fix issue with `title` in `new-entry`

pyproject.toml, requirements.txt, src/render_engine/cli/cli.py
Add support for a config file with defaults for:
- `module_site`
- `collection`
Issue #889 
- Explore what else might be in the config file.
- Explore adding creating the config file via `cookiecutter`
=> Use config for default `module:site` and `collection`

.github/workflows/scorecard.yml
According to Claude you can't have spaces in the SARIF name. This is a test to see if the renaming of the SARIF file fixes the security checks.
=> [TEST]:Rename Scorecard to fix security check issue

docs/docs/cli.md, tests/tests_cli/test_cli.py, tests/tests_cli/test_cli_commands.py
This PR significantly enhances the Render Engine CLI by adding comprehensive configuration options and new commands to improve the developer experience.
**Key Changes:**
- Added `pyproject.toml` configuration support for CLI defaults to avoid repetitive command-line arguments
- Added `templates` command for listing available templates from installed themes
- Added `new-entry` command for creating collection entries (blog posts, pages, etc.)
- Expanded documentation with detailed examples and usage tips for all commands
- Added comprehensive test coverage for new CLI functionality including argument parsing, config loading, and command operations
- Enhanced CLI interface with optional `module:site` parameters when using configuration defaults
The documentation has been significantly …
=> add tests and docs for cli

.github/release.yml
Configure GitHub's [automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) to exclude dependabot changes. This change intends to highlight feature and bugfixes rather than automated dependency upgrades in future changelog entries.
=> Exclude dependabot changes from changelog

.github/release.yml, .gitignore, docs/docs/cli.md, src/render_engine/cli/cli.py, tests/tests_cli/test_cli.py, tests/tests_cli/test_cli_commands.py
zAddresses issue #898 
- Add `include-date` option to `new-entry` to use the current date.
- Add validation for a date passed in via `--args`
- Always use `isoformat` for the date in the output of `new-entry`
- Add exception handling around parsing the config file.
- Fix hanging tests.
Build is still failing on trying to sort by the date from an entry.  This is seen by the following errors when trying to build/serve the site:
```
AttributeError: 'Page' object has no attribute 'date'
AttributeError: Cannot sort pages: 'date' attribute is missing from one or more pages.Make sure all pages in collection 'Blog' have the 'date' attribute
defined.
```
This is, I think, distinct from the issue #899.
Command run to create the entry:
```
render-engine new-entry test.md --include-date --args "date: …
```
=> issue-898 - Date validation for new-entry

.github/dependabot.yml, .gitignore
This change groups the dependencies into 3 groups production, developement, render-engien. We need to confirm that it works before closing the issue.
- [-] YES - Changes have been documented
- [-] YES - Changes have been tested
Confirm this actually works according to the docs it should work but I couldn't find any online examples for it.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#dependency-type-allow
=> possibly fix #845

.gitignore, src/render_engine/collection.py, src/render_engine/site.py, tests/test_plugins.py
The `pre_build_collection` and `post_build_collection` plugins were not actually being called.
=> Handle pre- and post-collection build plugins.

README.md, docs/docs/plugins.md, src/render_engine/collection.py, src/render_engine/plugins.py, src/render_engine/site.py, tests/test_plugins.py
Issue #923
- Fix issue where plugin settings were not being properly transmitted to the hooks.
- Fix issue with plugin hooks missing parameters
- Add `hook` property to `PluginManager` 
- Improve plugin documentation.
=> Fix issue with plugin settings not being properly passed into plugin hooks.

.github/workflows/test.yml, pyproject.toml, tests/test_feeds/test_feeds.py
- **fix datetime to make testing compatible with 3.10**
- **add 3.10 to ci/cd tests**
I'm combining the PRs so that 3.10 support fixed.
the fix was to change from  `datetime.UTC` to `datetime.timezone.utc`
=> use datetime timeznoe utc and adds support to 3.10

src/render_engine/cli/cli.py, src/render_engine/cli/event.py, src/render_engine/cli/utils.py, tests/tests_cli/test_cli.py, tests/tests_cli/test_render_engine_cli.py
Resolves issues #913 and #782
- Fix issues with `serve --reload` not actually re-rendering the site.
- Handle exceptions gracefully when they occur during a reload.
- Add `static` and `template` paths to watched for `serve --reload`.
It might not be a bad idea to have something that can catch user input as a way to exit the server cleanly. Possibly even force a `reload` so that changes to the python would also be handled.
=> Fix issues with `serve --reload`

docs/docs/collection.md, src/render_engine/collection.py, tests/test_collections.py
Add more flexibility to sorting a collection by allowing a `list` for `sort_by`
Do we want to add the ability to send a `Callable` as a sort key?
=> Add ability to use a `list` for collection sort.

docs/docs/cli.md
Resolves #965 by updating the documentation for how to configure the CLI via `pyproject.toml`
=> Fix documentation for CLI config in pyproject.toml

src/render_engine/_base_object.py, src/render_engine/collection.py, src/render_engine/page.py, src/render_engine/site.py, tests/test_plugins.py, tests/test_templates/test_base_html.py
Resolves issue #967
- `Page` objects handle their own rendering
- `Collection` objects handle their own rendering
- Update tests for changes needed to have `Page` and `Collection` handle their own rendering
NA
=> Have `Page` and `Collection` handle their own rendering.
