docs/mkdocs.yml

removes the show source from the API docs

remove source

---

src/render_engine/cli.py

typer requires the usage of typing.Optional still

ruff to ignore Optional

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

adds pr template

---

.chglog/CHANGELOG.tpl.md
.chglog/config.yml

Creates Changelog from [chglog](https://github.com/git-chglog)
Generate the first Changelog

Adds Changelog config from chglog

---

README.md
docs/docs/index.md

One typo and one small doc link fix.

:pencil: Small typos

---

docs/docs/getting-started/installation.md

Removes Getting Started

---

src/render_engine/cli.py
src/render_engine/render_engine_templates/create_app_py.txt
tests/create_app_check_file_no_site_vars.txt
tests/test_create_app.py

Correct Default SITE_TITLE and SITE_URL

---

docs/docs/templates.md
docs/mkdocs.yml
src/render_engine/archive.py
src/render_engine/collection.py
src/render_engine/engine.py
src/render_engine/site.py
tests/test_collections.py
tests/test_site.py

How should the route list be called in jinja templating

---

tests/test_plugins.py

updates tests on plugins

---

src/render_engine/collection.py
src/render_engine/site.py
tests/test_feeds.py

makes feed a public property

---

src/render_engine/collection.py
src/render_engine/engine.py

➕ Creates feed_url jinja built-it

---

src/render_engine/hookspecs.py
src/render_engine/site.py

creates the `post_render_content` plugin hookspec. This gives you access to the HTML of the rendered_page.

2023.7.1-create-post-render-content

---

src/render_engine/hookspecs.py
src/render_engine/site.py
tests/test_plugins.py

Create SITE_SETTINGS Attribute in site

---

src/render_engine/site.py

checks for default settings in plugins instead

---

src/render_engine/plugins/site_map.py

adds default settings to site map · 1d9b6e9c9e - Gitea: Git with a cup of tea

---

src/render_engine/site.py

ADDS register_themes

---

src/render_engine/site.py
src/render_engine/utils/themes.py

Over the next few updates, we'll be migrating `Site` to a composition model and the first is the `ThemeManager` that handles the output of the site. 
- management of static paths
- registering themes
- assignment of output_path
resolves #231 
#232

➕ adds theme manager

---

docs/docs/theme_management.md
src/render_engine/utils/themes.py
tests/test_theme_manager.py

add docs and Tests for ThemeManager

---

docs/mkdocs.yml

adds theme_manager to TOC

---

docs/docs/collection.md
docs/docs/getting-started/creating-a-collection.md

Updating docs to reference `template_vars` in `Collection` class as being passed to context as `collection`

update docs for template_vars in collection

---

src/render_engine/cli.py
src/render_engine/render_engine_templates/create_app_py.txt
tests/conftest.py
tests/test_cli.py
tests/test_create_app.py

Added the Author name and email to `render-engine init`
Fixes #269

render_engine init app.py should have site_vars and template_vars

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

ADD :book: Documentation to PR Template

---

src/render_engine/cli.py
src/render_engine/watcher/__init__.py
src/render_engine/watcher/event.py

- [x ] :dizzy: (New Feature)
No issue opened
Talked about it elsewhere.
Create testing

CLI --reload

---

pyproject.toml

add watchdog to dependencies

---

src/render_engine/cli.py
src/render_engine/render_engine_templates/create_app_py.txt
tests/tests_cli/conftest.py
tests/tests_cli/test_cli_builds_app.py

rename `AUTHOR` to `OWNER`

---

src/render_engine/cli.py
src/render_engine/watcher/__init__.py
src/render_engine/watcher/event.py

Made change to watcher/server to work with MacOS as well as the rebuild command working with the app.py file
- [ x] :bug: (bug)
resolves 300
N/A
Continue testing

Fix Watcher to Work in MacOS and Changes on App Module

---

src/render_engine/cli.py
src/render_engine/watcher/event.py

stop restarting server and fix ignore_patter

---

src/render_engine/render_engine_templates/create_app_py.txt
tests/tests_cli/test_cli_builds_app.py

corrects OWNER and NAVIGATION

---

src/render_engine/cli.py
src/render_engine/render_engine_templates/base.html
src/render_engine/render_engine_templates/content.html
src/render_engine/site.py
src/render_engine/utils/themes.py
tests/test_site.py
tests/test_theme_manager.py

adds head to register theme to look for insert point for themes in the base header.

adds head for them insertion and adds site.update_theme_settings

---

src/render_engine/site.py

Removes error by removing the attribute as it is currently not being used.

remove themes attribute from site

---

docs/docs/cli.md

resolves #321 
Improve documentation

adds docs for serve

---

src/render_engine/render_engine_templates/base.html
src/render_engine/site.py
src/render_engine/utils/themes.py
tests/test_templates/test_base_html.py

312-fix-reload-template-by-making-the-site-globals-a-set

---

pyproject.toml

fix pyproject.toml
https://peps.python.org/pep-0621/#requires-python

requires-python instead of python-requires

---

.github/workflows/test.yml

This pull request includes changes to the test workflow (`test.yml`). The most important changes include adding an `if`.
Main workflow changes:
* <a href="diffhunk://#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R4-R43">`.github/workflows/test.yml`</a>: Renamed the workflow, added an `if` condition to run the job only on workflow call events, added a strategy section for testing against multiple Python versions, and updated the `actions/checkout` step to version 2.

Add matrix for python versions

---

pyproject.toml
src/render_engine/cli/__init__.py

attempts to fix the cli call

---

.devcontainer/devcontainer.json
.github/CONTRIBUTION.md

black formatter is replaced with ruff

---

.all-contributorsrc

Fixes #377 
**Proposed Changes**
Changed the ```imageSize``` from 100 to 57 in the ```allcontributorsrc.json``` file

Reduced the size of the contributors image

---

.all-contributorsrc

Set contributorsSortAlphabetically in the .all-contributorsrc to true.
Fix #378

Fix: #378 update contributorsSortAlphabetically to sort contributors

---

.devcontainer/devcontainer.json

Add markdown tools to devcontainer

---

src/render_engine/__main__.py

Fixes #383 by making the import in `__main__` no longer relative.

`ImportDevcontainer - Error: attempted relative import with no known parent package`.

---

src/render_engine/cli/cli.py
tests/tests_cli/test_cli_builds_app.py

- [ X] :bug: (bug)
resolves #343 
add test cases?

add check for project-folder to exist when initilizing the project

---

CONTRIBUTING.md
docs/docs/contributing/CONTRIBUTING.md

ruff lint command issue

---

src/render_engine/cli/cli.py

Works to help complete #360 by converting the `serve` command to the typer annotated format.
#360

annotate render-engine serve

---

src/render_engine/cli/cli.py

This pull request removes an unnecessary if statement in the serve function, which improves code readability and simplifies the logic.

Remove unnecessary if statement in serve function

---

.github/workflows/lint.yml
src/render_engine/page.py
src/render_engine/site.py

This pull request updates the Python version to "3.12" in the project. It also includes some minor code improvements and fixes.

Update Python version

---

src/render_engine/site.py
src/render_engine/themes.py
tests/test_templates/test_base_html.py
tests/test_theme_manager.py

refactor `PrefixLoader` and `ChoiceLoader`

---

src/render_engine/cli/cli.py
src/render_engine/themes.py

closes #428  
Although the CLI command have been tested manually, It still lack a unit test

ClI command to see available templates

---

src/render_engine/cli/cli.py

fixed build cli doc string

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
tests/tests_cli/test_render_engine_init.py

Update PULL REQUEST TEMPLATE

---

docs/docs/archive.md
docs/docs/contributing/CONTRIBUTING.md
docs/docs/contributing/environment_setup.md
docs/docs/contributing/pages.md
docs/docs/custom_collections.md
docs/docs/getting-started/building-your-site.md
docs/docs/getting-started/creating-a-collection.md
docs/docs/getting-started/creating-a-page.md
docs/docs/getting-started/layout.md
docs/docs/parsers.md
docs/docs/plugins.md

Hey @kjaymiller,
I was going through the docs and thought it would be great to start by fixing these small typos and grammar mistakes.
I have asked some questions on discord RE render engine markdown parser once you clarify these things for me I'll start working on the markdown parser.

Improve docs

---

src/render_engine/collection.py

detailed warning for PageParser

---

.github/ISSUE_TEMPLATE/form_issue_template.yml
.github/PULL_REQUEST_TEMPLATE.md

Fix gh flows

---

src/render_engine/render_engine_templates/archive.html
src/render_engine/render_engine_templates/base_templates/_archive.html

Move the archive template to the base_templates folder

---

.github/workflows/publish.yml
.github/workflows/test.yml

update to trusted publisher model with render-engine

---

.github/workflows/test.yml

Fixes #551
Adds matrix for windows and macos-m1 testing

Add testing for MacOS and Windows

---

src/render_engine/themes.py
tests/test_site.py
tests/test_templates/test_base_html.py

Fixes #565
- Update Documentation to mention that the prefix is required.

533-raise-error-with-themes-that-have-no-prefix

---

src/render_engine/site.py

Fixes #566
- Add tests and Docs

[Bug]: Theme Templates are overwriting user_defined templates.

---

README.md

update to reference new wiki and revise

---

.github/workflows/test.yml
tests/test_plugins.py

Fixes #574 
Add tests and documentation for themes

⚗️ adds test for plugin - 574

---

docs/docs/theme_management.md

resolves #583 
Adds steps for adding your themes, changing the default template and static paths and registering themes.
- Check for tests for all documentation changes

update theming docs

---

docs/docs/theme_management.md
src/render_engine/site.py
tests/test_site.py

udpates the documentation around the theme management.
- corrects how to add static paths
adds the steps for updating the static_paths set

update documentation and lint tests

---

README.md
docs/docs/parsers.md

Check for tests on base parser and markdown page parser

update docs for base-parser and markdown parser

---

docs/docs/archive.md
docs/docs/cli.md
docs/docs/feeds.md
docs/docs/page.md
docs/docs/parsers.md

fix the space

---

docs/docs/page.md

remove backslash

---

src/render_engine/archive.py
src/render_engine/collection.py
tests/test_archive.py

Fixes #610 
Document Pagination

610 - fixes how num of pages

---

.github/workflows/test.yml

Hello,
As mentioned in the issue #615, I have simply removed the specified line present in **test.yml** located at _.github/workflows/_.
If at all there are any issues regarding these changes, then do let me know.
Sincere apologies if you find any errors from my end.
Hope these changes meet the requirements.
Thanks and Regards,
Mohit Kambli
Code Review.

Fix #615 : Remove this line

---

.github/workflows/test.yml
pyproject.toml
requirements.txt

fix #649 
related https://github.com/TvoroG/pytest-lazy-fixture/issues/65

Gh actions track dependency changes and remove lazy-fixture

---

.github/workflows/test.yml
requirements.txt

The folder names was written as file names so, the testing workflow was not running.
This PR fixes this issue.

Fix workflow

---

.github/workflows/test.yml
requirements.txt
src/render_engine/_base_object.py
src/render_engine/collection.py
tests/test_base_object.py
tests/test_plugins.py

add `plugin_settings`  to `BaseObject`

---

.github/workflows/test.yml
pyproject.toml

The summary is not the main thing to work with so I'm not too worried about the diff in GitHub actions. as long as it can be quickly downloaded from the test in case there is something that needs to be look at.
fixes #726

Jm adds coverage

---

pyproject.toml
requirements.txt

fixes the tests by adding the watchfiles package to pyproject.toml and requirements.txt

add watchfiles to requirements

---

pyproject.toml
requirements.txt

Adds httpx for testing

---

.github/workflows/test.yml

Add a Windows testing  matrix. 
closes #738

Create Windows Test

---

.github/workflows/test.yml

Add macOS testing workflow for release builds #747 
Fix Artifact Upload Conflict by Adding Unique Identifiers #748

Add macOS testing to release workflow

---

.github/workflows/test.yml

This PR fixes the coverage report, removes unnecessary job for macOS and includes it in the matrix for the previous latests job, tracks workflow changes for testing CI

track workflow changes in ci, fix coverage, remove extra job

---

.github/workflows/test.yml
README.md
docs/docs/getting-started/creating-your-app.md
docs/docs/getting-started/installation.md
docs/docs/index.md
pyproject.toml

- **reorganize pyproject.toml**
- **update pyproject.tmol**

758 fixing the install instructions on the cli

---

README.md

Removes the Warning on the README

Remove section from README

---

README.md
noxfile.py

add noxfile

---

.github/workflows/test.yml

Resolves #790 by adding a check for dependabot being the author based on https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#common-dependabot-automations

adds check for dependabot

---

src/render_engine/cli/cli.py
tests/tests_cli/test_render_engine_init.py

- [ x] :bug: (bug)
- [ x] YES - Changes have been tested

Update test fixture to include project_slug

---

docs/docs/cli.md
src/render_engine/cli/cli.py

fix module_site

---

docs/docs/theme_management.md

Update example for static files

---

docs/docs/theme_management.md

Clarify static_path management

---

.github/workflows/lint.yml
README.md

Fix workflows by not writing changes and failing on error, and separate the workflows.
fix #832
- [-] YES - Changes have been documented

832 fix auto formatting

---

src/render_engine/cli/cli.py

For `new-entry` make `filename` positional and add `slug` and `title` as kw args.

---

.github/workflows/scorecard.yml

Test scorecard workflow rename

---

.github/workflows/test.yml
.gitignore

1. Updated Python version matrix in `.github/workflows/test.yml`:
- Added Python 3.13 to the list of versions tested
- Changed single quotes to double quotes for consistency with cache parameter
This update expands our testing matrix to include Python 3.13, ensuring compatibility and stability on this new version.

update test versions

---

.github/release.yml
.github/workflows/test.yml
.gitignore
src/render_engine/engine.py
tests/test_blog.py
tests/test_feeds/test_feeds.py

This PR refactors datetime handling in the render engine to support both `datetime.datetime` and `datetime.date` objects, improves imports for better maintainability, and adds proper error handling for missing routes.

add datetime.date support

---

src/render_engine/page.py
tests/test_page.py

- Added `_data` property to `BasePage` class and updated the `_render_from_template` method to include it in the template context. 
- Added tests for both content and data properties.
The changes are ready for review.

allow data to be collected like content

---

pyproject.toml

Move `rich` to `dependencies` from `dev`

---

docs/docs/site.md
src/render_engine/site.py

- Removed partial attribute from Site class
- Removed _render_partial_collection() method from Site class
- Updated documentation in docs/site.md to remove references to partial rendering
- Cleaned up attribute documentation table formatting

BREAKING: remove partial collection

---

CONTRIBUTING.md
docs/docs/cli.md
docs/docs/contributing/CONTRIBUTING.md

Documentation udpate that better explains local setup with steps which include pre-commit and dockerfile setup.
It also mentions that this project uses nox and that all versions need passing tests.
- **remove partial collection (#926)**
- **Fix issue with plugin settings not being properly passed into plugin hooks. (#927)**
- **add pre-commit to contributor.md**

837 implement pre commit

---

README.md

Adds https://github.com/render-engine/render-engine-awesome-list to the `README.md`
Keep adding things to the awesome list.

Add a link to the awesome list to the README.md
